### ISSUE TITLE
Preliminary review based on first milestone

### ISSUE THREAD

**Issue by addianto** [azzuhripasaribu/PBD-Final-Project#1]
Hello @azzuhripasaribu @dhiwarya,

The following is my initial assessments on your final group project:

## Project Documentation

-  The documentation in `README.md` contains adequate information according to the grading rubric. It is still missing badges that showing information regarding the project.
-  I think you need to distinguish **user roles** and **work distribution**. User roles meant the types of users in the app (backend & frontend) and the features that accessible by each type of user. Meanwhile, work distribution is the assignment of responsibility for each group member in working on the group project.
-  The basic instruction to develop and run the app locally need to include the instruction to download Flutter dependencies, e.g. `flutter pub get`.

## Release Artefact

-  Good job on automating releases to GitHub. It is still can be improved by making separate jobs for building the **debug** and **release** variants of the app. The **debug** variant is the one that usually released for internal quality assurance by the development team. The **release** variant is the build that will be published on a marketplace such as Google Play. 
-  Try to include automated quality assurance GitHub Actions such as executing `flutter analyze` on each new commit.

## Individual Assessments

I have not checked the contributions made by each group member.
Make sure everyone has been invited as developer/collaborator in the group project's GitHub repository.

## Actionable Tasks

-  [ ] Add badges to `README.md`
-  [ ] Describe the work distribution of each group member
-  [ ] Describe the user roles (see my comment above)
-  [ ] Resolve any issues reported by `flutter analyze`

That is all from me. Good job.
